-- customize mason plugins
return {
  -- use mason-lspconfig to configure LSP installations
  {
    "williamboman/mason-lspconfig.nvim",
    -- overrides `require("mason-lspconfig").setup(...)`
    opts = {
      ensure_installed = {
        "astro",
        "ansiblels",
        "antlersls",
        "clangd",
        "cssls",
        "cssmodules_ls",
        "cucumber_language_server",
        "bashls",
        "clangd",
        "cmake",
        "cssls",
        "diagnosticls",
        "dockerls",
        "docker_compose_language_service",
        "elixirls",
        "elmls",
        "emmet_ls",
        "esbonio",
        "flux_lsp",
        "golangci_lint_ls",
        "gopls",
        "html",
        "jsonls",
        "lua_ls",
        "marksman",
        "neocmake",
        "grammarly",
        "pyright",
        "ruby_ls",
        "rust_analyzer",
        "taplo",
        "terraformls",
        "tflint",
        "tsserver",
      },
    },
  },
  -- use mason-null-ls to configure Formatters/Linter installation for null-ls sources
  {
    "jay-babu/mason-null-ls.nvim",
    opts = {
      ensure_installed = {
        "actionlint",
        "black",
        "buf",
        "bufls",
        "cfn-lint",
        "colorgen-nvim",
        "commitlint",
        "cpplint",
        "cmakelang",
        "delve",
        "djlint",
        "elm-format",
        "erb-lint",
        "goimports",
        "golangci-lint",
        "golines",
        "hadolint",
        "isort",
        "jq",
        "mypy",
        "markdownlint",
        "prettier",
        "prettierd",
        "protolint",
        "rstcheck",
        "rubocop",
        "selene",
        "shellcheck",
        "stylua",
        "shfmt",
      },
    },
  },
  {
    "jay-babu/mason-nvim-dap.nvim",
    opts = {
      ensure_installed = {
        "bash",
        "bash-debug-adapter",
        "bzl",
        "cppdbg",
        "cpptools",
        "debugpy",
        "delve",
        "go-debug-adapter",
        "js",
        "js-debug-adapter",
        "php",
        "python",
      },
    },
  },
}
